# Generated by Django 5.1.4 on 2025-01-08 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='submitted_at',
            new_name='created_at',
        ),
    ]
