# Generated by Django 5.1.4 on 2025-01-09 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0005_user_delete_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
