# Generated by Django 5.1.4 on 2025-01-09 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0007_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
