# Generated by Django 5.1.4 on 2025-01-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0008_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snacks', 'Snacks'), ('Desserts', 'Desserts')], max_length=50)),
                ('cuisine', models.CharField(max_length=100)),
                ('prep_time', models.PositiveIntegerField()),
                ('cook_time', models.PositiveIntegerField()),
                ('servings', models.PositiveIntegerField()),
                ('ingredients', models.TextField()),
                ('steps', models.TextField()),
                ('calories', models.PositiveIntegerField()),
                ('carbs', models.PositiveIntegerField()),
                ('protein', models.PositiveIntegerField()),
                ('fat', models.PositiveIntegerField()),
                ('tags', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
