# Generated by Django 5.1.4 on 2025-01-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0009_recipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['name'], 'verbose_name': 'Recipe', 'verbose_name_plural': 'Recipes'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='calories',
            field=models.PositiveIntegerField(verbose_name='Calories per Serving'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='carbs',
            field=models.PositiveIntegerField(verbose_name='Carbohydrates (grams)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snacks', 'Snacks'), ('Desserts', 'Desserts')], max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.PositiveIntegerField(verbose_name='Cooking Time (minutes)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cuisine',
            field=models.CharField(max_length=100, verbose_name='Cuisine Type'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='fat',
            field=models.PositiveIntegerField(verbose_name='Fat (grams)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(verbose_name='List of Ingredients'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Recipe Name'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.PositiveIntegerField(verbose_name='Preparation Time (minutes)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='protein',
            field=models.PositiveIntegerField(verbose_name='Protein (grams)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.PositiveIntegerField(verbose_name='Number of Servings'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=models.TextField(verbose_name='Preparation Steps'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tags (comma-separated)'),
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_plan_title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('meal_type', models.CharField(choices=[('Vegetarian', 'Vegetarian'), ('Vegan', 'Vegan'), ('High Protein', 'High Protein'), ('Low Carb', 'Low Carb'), ('Balanced', 'Balanced')], max_length=50)),
                ('days', models.CharField(max_length=255)),
                ('calories_goal', models.IntegerField(blank=True, null=True)),
                ('protein_goal', models.IntegerField(blank=True, null=True)),
                ('carbs_goal', models.IntegerField(blank=True, null=True)),
                ('fat_goal', models.IntegerField(blank=True, null=True)),
                ('meal_plan_image', models.ImageField(blank=True, null=True, upload_to='meal_plan_images/')),
                ('recipes', models.ManyToManyField(to='Landing.recipe')),
            ],
        ),
    ]
