# Generated by Django 5.1.4 on 2025-01-10 17:22

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0010_alter_recipe_options_alter_recipe_calories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=56),
        ),
    ]
