# Generated by Django 5.1.4 on 2025-01-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0011_alter_mealplan_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('content_type', models.CharField(choices=[('Article', 'Article'), ('Video', 'Video'), ('Guide', 'Guide'), ('Infographic', 'Infographic'), ('Other', 'Other')], max_length=50)),
                ('topic_category', models.CharField(choices=[('Nutrition', 'Nutrition'), ('Meal Planning', 'Meal Planning'), ('Fitness', 'Fitness'), ('Mental Health', 'Mental Health'), ('Wellness', 'Wellness')], max_length=50)),
                ('upload_file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('content_link', models.URLField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
