# Generated by Django 5.1.4 on 2025-01-12 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0014_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
