# Generated by Django 5.1.4 on 2025-01-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0015_delete_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='tags',
            field=models.CharField(blank=True, choices=[('Macronutrients', 'Macronutrients'), ('Micronutrients', 'Micronutrients')], max_length=20),
        ),
    ]
